### ISSUE TITLE
Review Lab5, 2020-12-15

### ISSUE THREAD

**Issue by Ironedde** [viktorfrom/klee_tutorial#2]
As Mark mentions in [his issue](https://github.com/viktorfrom/klee_tutorial/issues/1#issue-767568811) it is peculiar that you get zero in both the start and stop variables when running `cargo_klee_examples/examples/cyccnt.rs`.
Is this the test that is marked as the one that causes an abort? I would go back and recheck.
And if it is infact the one that causes the abort, I would ask Per for advice because a `let _time : u8 = 0 - 0;` shouldn't break you program (as Mark also mentioned).

Furthermore I have some notes:

- [`cargp_klee_examples/examples/array.rs : A`](https://github.com/viktorfrom/klee_tutorial/blob/2ae864521aea2d0678a5ada5a8c0e786bf1322ac/cargo_klee_examples/examples/array.rs#L52) - As to why the relese version only has 2 tests, the compiler has basically optimized away the code for the loop function. Instead it has inserted a check for the value 9, and if it's true the program panics. This can be verified using gdb and checking the assembly code.

- `get_sign.rs` - I saw that you got another hash then myself, but this could just be that you run another version of the compiler than I am. But it might be something to keep in mind while debugging the error (or lack thereof) discussed above.

Other then that it looks good.
@ me if you have any question

**Comment by viktorfrom** [comment]
Yes! I do agree the `let _time : u8 = 0 - 0;` result was strange and possibly wrong, however I ran it several times and kept getting the same answer so I rolled with it. I guess I have to ask Per tomorrow. 

I believe the hash is randomly generated each time you run the script. I've re-cloned the repo one or two times too many and I kept getting different hashes. I don't think it's supposed to be identical.

**Comment by Ironedde** [comment]
Did you ever get to the bottom of why the start and end values were both zero for the abort test case?

**Comment by viktorfrom** [comment]
> Did you ever get to the bottom of why the start and end values were both zero for the abort test case?

No, I tried re-running the tests yesterday but I was not able to produce a different result. Couldn’t really figure out the reason why either.
